[package]
name = "disp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
postgres = {version = "0.19.7", features = ["with-uuid-1"]}
uuid = {version = "1.8.0", features = ["v4", "serde"]}
